### ISSUE TITLE
Get-ProfileBanner.ps1 version check

### ISSUE THREAD

**Issue by jasonrush** [GavinEke/GAT#1]
If it's checking the major version is greater-than/equal-to 5 and minor version is greater-than/equal-to 1 as two separate checks, this version check would fail for 6.0, 7.0, etc down the road, right?

Should probably be something like:
    If ($PSVersionTable.PSVersion.Major -gt 5 -or ( $PSVersionTable.PSVersion.Major -eq 5 -and $PSVersionTable.PSVersion.Minor -ge 1) ) {

**Comment by GavinEke** [comment]
Yes 6.0, 7.0 etc will fail thanks for pointing that out when I have access to a computer again I will fix this.

I might change the test to the following: (pending it works)

    If ([version]$PSVersionTable.PSVersion -ge [version]'5.1.0.0') {

**Comment by GavinEke** [comment]
Testing change appears to fix the issue. Thank you again for reporting.
